version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: persondb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: persondb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build:
      context: ../QueryDb  # Itt add meg a C# projekt mappáját
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=persondb;Username=myuser;Password=asdf
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  pgdata: {}
